FROM python:3.7.0

ARG USER_NAME
RUN useradd $USER_NAME -s /bin/bash -m

RUN pip install --upgrade pip
WORKDIR /home/$USER_NAME/
RUN pip install --no-warn-script-location mlflow==1.1 

USER $USER_NAME
WORKDIR /home/$USER_NAME
EXPOSE 5000

CMD    mlflow server \
       --backend-store-uri=mlruns \
       --host=0.0.0.0 \
       --port=5000

