FROM jupyter/pyspark-notebook:latest

ARG USER_NAME
ARG PROJECT_NAME
USER root

RUN pip install --upgrade jupyterlab
RUN pip install --upgrade jupyter

COPY config/jupyter_notebook_config.py /home/jovyan/.jupyter/jupyter_notebook_config.py

COPY ./requirements.txt /home/$USER_NAME/requirements.txt
RUN pip install -r /home/$USER_NAME/requirements.txt && \
    fix-permissions $CONDA_DIR && \
    fix-permissions /home/$USER_NAME

# jupyter nbextensions
RUN pip install jupyter_contrib_nbextensions && \
    jupyter contrib nbextension install 

# template when initiating notebook
RUN mkdir /opt/conda/lib/python3.7/site-packages/jupyter_contrib_nbextensions/nbextensions/setup
COPY ./config/nbextension_setup/main.js /opt/conda/lib/python3.7/site-packages/jupyter_contrib_nbextensions/nbextensions/setup/
COPY ./config/nbextension_setup/setup.yaml /opt/conda/lib/python3.7/site-packages/jupyter_contrib_nbextensions/nbextensions/setup/
COPY ./config/nbextension_setup/README.md /opt/conda/lib/python3.7/site-packages/jupyter_contrib_nbextensions/nbextensions/setup/
RUN jupyter contrib nbextension install && \
    jupyter nbextension enable setup/main

# code-folding in notebook
RUN jupyter nbextension enable codefolding/main

# Table-Of-Contents extension
RUN jupyter labextension install @jupyterlab/toc --no-build && \
    jupyter nbextension enable toc2/main

# collapsible-headings
RUN jupyter nbextension enable collapsible_headings/main
RUN jupyter labextension install @aquirdturtle/collapsible_headings --no-build

# snippets for lab and notebook
RUN pip install jupyterlab-snippets && \
    jupyter nbextension enable snippets_menu/main && \
    jupyter nbextension enable snippets/main


# JupyterLab-Git extension
RUN jupyter labextension install @jupyterlab/git && \
    pip install --upgrade jupyterlab-git && \
    jupyter serverextension enable --py jupyterlab_git

# ipywidgets
RUN pip install ipywidgets
RUN pip install --upgrade jupyterlab
RUN jupyter lab build && \
    jupyter labextension enable jupyterlab/toc && \
    jupyter labextension enable aquirdturtle/collapsible_headings


USER $NB_USER
WORKDIR /home/$NB_USER/$PROJECT_NAME
