FROM python:3.7.0

ARG USER_NAME
ARG PROJECT_NAME
ARG UID
ARG GUID

RUN groupadd -g $GUID projectgroup
RUN useradd -m -u $UID -g $GUID -s /bin/bash $USER_NAME

RUN pip install --upgrade pip
RUN pip install --no-warn-script-location mlflow==1.1

USER $USER_NAME
WORKDIR /home/$USER_NAME/$PROJECT_NAME
EXPOSE 5000

#initiate empty experiment 0
#RUN mlflow experiments create -n 0
CMD    mlflow server \
       --backend-store-uri=file://`pwd`/mlruns \
       --host=0.0.0.0 \
       --port=5000

